<?php
require_once 'includes/db.php';
require_once 'includes/auth.php';
require_once 'tcpdf/tcpdf.php'; // Adjust path if needed

$studentEmail = $_SESSION['user']['email'];

// Fetch student details
$query = "SELECT * FROM students WHERE email = '$studentEmail'";
$result = $conn->query($query);

if (!$result || $result->num_rows === 0) {
    die("Student not found.");
}

$student = $result->fetch_assoc();
$roll = $student['roll_no'];

// Fetch marks
$marksQuery = "SELECT * FROM marks WHERE roll_no = '$roll'";
$marksResult = $conn->query($marksQuery);

if (!$marksResult || $marksResult->num_rows === 0) {
    die("Marks not found.");
}

$marks = $marksResult->fetch_assoc();
$subjects = ['python', 'web_tech', 'mis', 'sad', 'research'];

// GPA & Grade calculation
$total = 0;
$rows_html = '';
foreach ($subjects as $index => $subject) {
    $score = $marks[$subject];
    $total += $score;

    $gpa = min(round($score / 25, 2), 4.0); // GPA calculation max 4.0

    // Assign grade based on GPA
    $grade = match (true) {
        $gpa >= 4.0 => 'A+',
        $gpa >= 3.6 => 'A',
        $gpa >= 3.2 => 'B+',
        $gpa >= 2.8 => 'B',
        $gpa >= 2.4 => 'C+',
        $gpa >= 2.0 => 'C',
        default => 'F',
    };

    // Alternate row color for readability
    $bgcolor = ($index % 2 == 0) ? '#f2f2f2' : '#ffffff';

    $rows_html .= "
        <tr style=\"background-color: $bgcolor;\">
            <td style=\"padding:8px; text-align:center;\">" . strtoupper($subject) . "</td>
            <td style=\"padding:8px; text-align:center;\">$score</td>
            <td style=\"padding:8px; text-align:center;\">$gpa</td>
            <td style=\"padding:8px; text-align:center;\">$grade</td>
        </tr>
    ";
}

$average = $total / count($subjects);
$final_gpa = min(round($average / 25, 2), 4.0);

// Create PDF document
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator('Resultify');
$pdf->SetAuthor('Lumbini Technological University');
$pdf->SetTitle('Student Marksheet');
$pdf->SetMargins(15, 20, 15);
$pdf->AddPage();
$pdf->SetFont('dejavusans', '', 12);

// HTML content for PDF
$html = <<<EOD
<style>
    h2, h3 {
        text-align: center;
        color: #4a4a4a;
        margin-bottom: 10px;
    }
    h3 {
        margin-top: 0;
        font-weight: 600;
    }
    .student-info p {
        font-size: 12pt;
        margin: 6px 0;
    }
    table {
        border-collapse: collapse;
        width: 100%;
        margin-top: 20px;
        margin-bottom: 20px;
        font-size: 12pt;
        font-family: dejavusans, sans-serif;
        line-height: 1.6;
    }
    th {
        background-color: #6b5b95;
        color: white;
        padding: 14px 10px;
        text-align: center;
        font-weight: 700;
        letter-spacing: 0.05em;
    }
    td {
        border: 1px solid #ddd;
        padding: 12px 10px;
        text-align: center;
        vertical-align: middle;
    }
    .total-row td {
        font-weight: 700;
        background-color: #e0e0e0;
        padding: 14px 10px;
    }
    .footer-text {
        margin-top: 25px;
        font-weight: 600;
        font-size: 12pt;
        text-align: center;
        color: #333;
    }
</style>


<h2>Lumbini Technological University</h2>
<h3>Student Marksheet</h3>

<div class="student-info">
    <p><strong>Name:</strong> {$student['name']}</p>
    <p><strong>Roll No:</strong> {$student['roll_no']}</p>
    <p><strong>Email:</strong> {$student['email']}</p>
    <p><strong>Department:</strong> {$student['department']}</p>
</div>

<table>
    <thead>
        <tr>
            <th>Subject</th>
            <th>Marks</th>
            <th>GPA</th>
            <th>Grade</th>
        </tr>
    </thead>
    <tbody>
        $rows_html
        <tr class="total-row">
            <td><strong>Total</strong></td>
            <td><strong>$total</strong></td>
            <td colspan="2"></td>
        </tr>
        <tr class="total-row">
            <td><strong>Overall GPA</strong></td>
            <td colspan="3"><strong>$final_gpa </strong></td>
        </tr>
    </tbody>
</table>

<p class="footer-text">Result generated by Resultify | Lumbini Technological University</p>
EOD;

// Write HTML content to PDF
$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output('marksheet_' . $student['roll_no'] . '.pdf', 'D'); // 'D' for download
?>
